name: Pipeline_Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      -main

jobs:
  Deploy-development:
    runs-on: unbuntu-latest

    steps:
      - name: "checkout code"
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercell pull --yes --environment=development --tokens=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel buils --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts To Vercel
        run: vercel deploy --prebuilt --tokens=${{ secrets.VERCEL_TOKEN }}

      
